config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for 'admin/users', controllers: {
    sessions: 'admin_users/sessions'
  }

  devise_scope 'admin/users' do
    get '/' => 'admin_users/sessions#new'
    get '/admin_users/sign_out' => 'admin_users/sessions#destroy'
  end

  namespace :admin do
    get '/' => 'categories#index'
    get 'index' => 'users#index'
    resources :admin_users, controller: :manage_roles

    resource :app_configs, only: %i(edit update)

    Master.master_routes.keys.each do |type|
      resources type, controller: :masters, type: type.classify
    end

    resources :categories
    resources :sub_categories
  end

  mount Versions::V1::Api => '/'
  mount GrapeSwaggerRails::Engine => '/api/swagger'

end

app/controllers/admin/manage_roles_controller.rb
module Admin
  class ManageRolesController < Admin::ApplicationController
    before_action :authenticate_admin_user!
    before_action :set_instance, only: [:edit, :update, :destroy]
    #before_action :special_admin_only_accessible

    def index
      @page = params[:page] || 1
      @admin_users = Admin::User.all.page(@page).per(Settings.paging_per.manage_roles.list)
      render template: 'admin/manage_roles/index'
    end

    def new
      @admin_user = Admin::User.new
      render template: 'admin/manage_roles/form'
    end

    def create
      @admin_user = Admin::User.new(admin_user_params)
      @admin_user.save ? success_message(:created) : failure_message
    end

    def edit
      render template: 'admin/manage_roles/form'
    end

    def update
      @admin_user.update(admin_user_params(true)) ? success_message(:updated) : failure_message
    end

    def destroy
      @admin_user.soft_destroy
      flash[:success] = I18n.t('admin_user.message.deleted')
      redirect_to action: :index
    end

    private

    def set_instance
      @admin_user = Admin::User.find(params[:id])
    end

    def admin_user_params(is_update = false)
      if is_update && params[:admin_user][:password].blank? && params[:admin_user][:password_confirmation].blank?
        params.require(:admin_user).permit(:name, :email, :role)
      else
        params.require(:admin_user).permit(:name, :email, :password, :password_confirmation, :role)
      end
    end

    def success_message(i18n_key)
      flash[:success] = I18n.t(i18n_key, scope: 'admin_user.message')
      redirect_to action: :index
    end

    def failure_message
      flash.now[:alert] = @admin_user.errors.full_messages.join('<br/>').html_safe
      render template: 'admin/manage_roles/form'
    end
  end
end

app/views/admin/manage_roles/form.html.erb
<!-- Content Header (Page header) -->

<%
controller_name = controller.controller_name
action = controller.action_name.to_sym
model = Object.const_get('Admin::User')
%>

<div class="content-header">
  <div class="container-fluid">
    <%= flash_messages %>
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">

      <!-- /.col-md-6 -->
      <div class="col-lg-12">

        <div class="card">
          <!-- /.card-header -->

          <section class="content">
          <% url_for_upsert = @admin_user.persisted? ? admin_admin_user_path : admin_admin_users_path %>
          <% action = @admin_user.persisted? ? :update : :create %>
          <%= form_with(model: @admin_user, :url => {:action => action} , local: true) do |form| %>

          <!-- <% if @admin_user.errors.any? %>
            <div id="error_explanation">
              <span>入力内容を確認してください</span>
              <ul>
                <% @admin_user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>  -->
            <div class="card-body">
              <div class="form-group col-sm-6">
                <%= form.label model.human_attribute_name :name %><!-- <span class="badge badge-danger">必須</span> -->
                <%= form.text_field :name, class:"form-control", placeholder:"名前を入力してください" %>
              </div>

              <div class="form-group col-sm-6">
                <%= form.label model.human_attribute_name :email %><!-- <span class="badge badge-danger">必須</span> -->
                <%= form.text_field :email, class:"form-control", placeholder:"メールアドレス" %>
              </div>

              <div class="form-group col-sm-6">
                <%= form.label model.human_attribute_name :password %><!-- <span class="badge badge-danger">必須</span> -->
                <%= form.password_field :password, class:"form-control" %>
              </div>

              <div class="form-group col-sm-6">
                <%= form.label model.human_attribute_name :password_confirmation %><!-- <span class="badge badge-danger">必須</span> -->
                <%= form.password_field :password_confirmation, class:"form-control"%>
              </div>

              <div class="form-group col-sm-6">
                <%= form.label model.human_attribute_name :role %><!-- <span class="badge badge-danger">必須</span> -->
                <%= form.select :role, Admin::User.roles_i18n.invert, {selected: @admin_user.persisted? ? @admin_user.role : ""}, {class: "custom-select" , required: true } %>
              </div>

            </div>
            <div class="card-footer">
              <%= form.submit @admin_user.persisted? ? I18n.t('helpers.submit.update') : I18n.t('helpers.submit.create') , class:"btn btn-sm btn-primary" %>
              <% if @admin_user.persisted? %>
                <%= link_to '削除', admin_admin_user_path(@admin_user), method: :delete, class:"btn btn-sm btn-danger", data: { confirm: '本当によろしいでしょうか？' } %></td>
              <% end %>
              <%= link_to admin_admin_users_path, type: :button, class:"btn btn-sm btn-secondary float-right" do %>
                <%= I18n.t('helpers.submit.back') %>
              <% end %>

            </div>
          <% end %>
          </section>


          <!-- /.card-body -->
        </div>

      </div>
      <!-- /.col-md-6 -->
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content -->

app/views/admin/manage_roles/index.html.erb
<!-- Content Header (Page header) -->

<%
controller_name = controller.controller_name
action = controller.action_name.to_sym
model = Object.const_get('Admin::User')
%>

<div class="content-header">
  <div class="container-fluid">
    <%= flash_messages %>
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">

      <!-- /.col-md-6 -->
      <div class="col-lg-12">

        <div class="card">
          <div class="card-header ui-sortable-handle" style="cursor: move;">
                <h3 class="card-title">
                  <i class="ion ion-clipboard mr-1"></i>
                  <%= model.to_s %>
                </h3>
                <%= link_to(I18n.t('helpers.submit.create'),  {action: :new},  class: "btn btn-sm btn-info float-right" ) %>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="users_example" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th></th>
                  <th><%= model.human_attribute_name :name %></th>
                  <th><%= model.human_attribute_name :email %></th>
                  <th><%= model.human_attribute_name :role %></th>
                  <!-- <th></th>
                  <th></th> -->
                </tr>
              </thead>

              <tbody>
                <% @admin_users.each do |user| %>
                  <tr data-href="<%= url_for("/admin/admin_users/#{user.id}/edit") %>">
                    <td><%= user.id %></td>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.role %></td>
                    <!--
                    <td><%= link_to '編集', edit_admin_admin_user_path(user), class:"btn btn-outline-primary btn-sm" %></td>
                    <td><%= link_to '削除', admin_admin_user_path(user), method: :delete, class:"btn btn-outline-danger btn-sm", data: { confirm: '本当によろしいでしょうか？' } %></td>
                    -->
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->

          <div class="card-footer clearfix">
            <%= paginate @admin_users %>
          </div>

        </div>

      </div>
      <!-- /.col-md-6 -->
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content -->