config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for 'admin/users', controllers: {
    sessions: 'admin_users/sessions'
  }

  devise_scope 'admin/users' do
    get '/' => 'admin_users/sessions#new'
    get '/admin_users/sign_out' => 'admin_users/sessions#destroy'
  end

  namespace :admin do
    get '/' => 'categories#index'
    get 'index' => 'users#index'
    resources :admin_users, controller: :manage_roles

    resource :app_configs, only: %i(edit update)

    Master.master_routes.keys.each do |type|
      resources type, controller: :masters, type: type.classify
    end

    resources :categories
    resources :sub_categories
  end

  mount Versions::V1::Api => '/'
  mount GrapeSwaggerRails::Engine => '/api/swagger'

end

app/views/admin/layouts/_alert.html.erb
<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert">
     <%= value %>
   </div>
<% end %>

app/views/admin/layouts/_footer.html.erb
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-<%= Date.today.year %> <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

app/views/admin/layouts/_navbar.html.erb
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/" class="nav-link">Home</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
          </li>
        </ul>

        <!-- SEARCH FORM -->
        <!--
        <form class="form-inline ml-3">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
        -->

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, class: "nav-link" %>
            <!-- a class="nav-link" data-widget="control-sidebar" data-slide="true" href="/admin_users/sign_out" role="button">
              Log out <%= current_admin_user.name %>
            </a -->
          </li>
        </ul>
      </nav>
      <!-- /.navbar -->

app/views/admin/layouts/_sidebar.html.erb
      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <%= link_to admin_index_path, class:"brand-link" do %>
          <img src="<%= image_path 'AdminLTELogo.png' %>" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
               style="opacity: .8">
          <span class="brand-text font-weight-light">管理画面サンプル</span>
        <% end %>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar user panel (optional) -->

          <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info bg-gray-dark">
              <%= current_admin_user.name %>
            </div>
          </div>

          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <!-- Add icons to the links using the .nav-icon class
                   with font-awesome or any other icon font library -->

             <li class="nav-item">
              <%= link_to admin_categories_path, class:"nav-link" do %>
                <i class="nav-icon fas fa-th"></i>
                <p>
                  カテゴリ
                </p>
              <% end %>
             </li>
             <li class="nav-item">
              <%= link_to admin_sub_categories_path, class:"nav-link" do %>
                <i class="nav-icon fas fa-th"></i>
                <p>
                  サブカテゴリ
                </p>
              <% end %>
             </li>
              <li class="nav-item has-treeview"> <!-- menu-open -->
                <a href="#" class="nav-link"> <!-- active -->
                  <i class="nav-icon fas fa-th"></i>
                  <p>
                    Master
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <%
                  Master.master_routes.each do |key, value| %>
                    <li class="nav-item">
                      <%= link_to "/admin/" + key, class:"nav-link" do %>
                        <i class="far fa-circle nav-icon"></i>
                        <p><%= value %></p>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </li>
              <li class="nav-item">
               <%= link_to admin_admin_users_path, class:"nav-link" do %>
                 <i class="nav-icon fas fa-th"></i>
                 <p>
                   管理者管理
                 </p>
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to edit_admin_app_configs_path, class:"nav-link" do %>
                 <i class="nav-icon fas fa-th"></i>
                 <p>
                   全体設定
                 </p>
               <% end %>
              </li>

            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>

<script>
$(function () {
  var url = window.location;
  //console.log(url);
  $('ul.nav-sidebar a').filter(function() {
        return this.href == url || url.href.indexOf(this.href) == 0;
  }).addClass('active');

  $('ul.nav-sidebar a').filter(function() {
        return this.href == url || url.href.indexOf(this.href) == 0;
  }).parent().parent().parent().addClass('menu-open');
});
</script>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理画面</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>

  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Navbar -->
      <%= render 'admin/layouts/navbar' %>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <%= render 'admin/layouts/sidebar' %>
      <!-- / Main Sidebar Container -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <%= yield %>
      </div>
      <!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
          <h5>Title</h5>
          <p>Sidebar content</p>
        </div>
      </aside>
      <!-- /.control-sidebar -->

      <!-- Main Footer -->
      <%= render 'admin/layouts/footer' %>
      <!-- / Main Footer -->

    </div>
    <!-- ./wrapper -->
  </body>

<script>
$(function () {
  $('tbody tr[data-href]').addClass('clickable').click( function() {
    window.location = $(this).attr('data-href');
  }).find('a').hover( function() {
      $(this).parents('tr').unbind('click');
  }, function() {
      $(this).parents('tr').click( function() {
          window.location = $(this).attr('data-href');
      });
  });
});
</script>

</html>